cookie:
  expiry_days: 30
  key: cristi
  name: ai_detector_cookie
credentials:
  username_in_email: true
  usernames:
    cristiantudor:
      email: cristian.tudor@ipsos.com
      failed_login_attempts: 0
      first_name: Cristian
      last_name: Tudor
      logged_in: true
      password: $2b$12$vTHoQuvg5ZxsG52eULy2gesQwJebCH86Y92DxPUMyfTFspDFHDfX2
      password_hint: Admin
      roles: null
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: $2b$12$wlUEPo7FSJ6KlnGWWyqueuY01xJydu2aTT6kbtoSofshdaOLlrKcW
