version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: api
    # CORRECTED COMMAND: We run from the project root, so Python can see the 'app' package.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app # Mount the entire project root to /app
      - ./model/detector_model:/app/model/detector_model 
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: worker
    # CORRECTED COMMAND: We run from the project root.
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - .:/app # Mount the entire project root to /app
      - ./model/detector_model:/app/model/detector_model
      - db-data:/app/db
    depends_on:
      - redis
    networks:
      - app-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./assets:/app/assets
    depends_on:
      - api
    networks:
      - app-network

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: monitoring
    ports:
      - "8502:8501"
    volumes:
      - db-data:/app/db
    depends_on:
      - worker
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge