FROM python:3.11.3

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the new dashboard script into the container
COPY ./monitoring_dashboard.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "monitoring_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]