version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks: # Add this
      - app-network # Add this

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
      - ./model/detector_model:/app/model/detector_model 
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks: # Add this
      - app-network # Add this

  worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: worker
    command: celery -A worker worker --loglevel=info
    volumes:
      - ./app:/app
      - ./model/detector_model:/app/model/detector_model
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks: # Add this
      - app-network # Add this

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks: # Add this
      - app-network # Add this

# Add this entire block at the end of the file
networks:
  app-network:
    driver: bridge