
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - api
      - dashboard
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    working_dir: /code # Explicitly set the working directory
    # No ports here
    volumes:
      - ./model/detector_model:/code/model/detector_model
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: worker
    command: celery -A app.worker worker --loglevel=info
    working_dir: /code # Explicitly set the working directory
    # No ports here
    volumes:
      - ./model/detector_model:/code/model/detector_model
      - db-data:/database
    depends_on:
      - redis
    networks:
      - app-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: dashboard
    # No ports here
    volumes:
      - ./assets:/app/assets
      - ./config.yaml:/app/config.yaml
    depends_on:
      - api
    networks:
      - app-network
  
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: monitoring
    ports:
      - "8502:8501"
    volumes:
      - db-data:/database
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge